apiVersion: apps/v1
kind: Deployment
metadata:
  name: typebot
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: typebot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: typebot
    spec:
      containers:
        - name: typebot
          envFrom:
            - configMapRef:
                name: typebot
            - secretRef:
                name: typebot
          image: typebot-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 1536Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
