apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: typebot-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: eddie.us-east-1.dev.cloudhumans.io
      http:
        paths:
          - path: /viewer
            pathType: ImplementationSpecific
            backend:
              service:
                name: typebot
                port:
                  number: 81
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: typebot
                port:
                  number: 80
  tls:
    - hosts:
        - eddie.us-east-1.dev.cloudhumans.io
      secretName: typebot-tls-secret
