apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: typebot

commonLabels:
  app: typebot

resources:
  - namespace.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
