apiVersion: v1
kind: Service
metadata:
  labels:
    app: typebot
  name: typebot
spec:
  ports:
    - name: http-main
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: http-viewer
      port: 81
      protocol: TCP
      targetPort: 3001
  selector:
    app: typebot
  sessionAffinity: None
  type: ClusterIP
