apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  environment: prd

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: typebot-builder-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: eddie.us-east-1.prd.cloudhumans.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: eddie.us-east-1.prd.cloudhumans.io
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: typebot-viewer-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: eddieeyes.us-east-1.prd.cloudhumans.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: eddieeyes.us-east-1.prd.cloudhumans.io        
  - target:
      version: v1
      kind: ConfigMap
      name: typebot
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: replace
        path: /data/NEXTAUTH_URL
        value: https://eddie.us-east-1.prd.cloudhumans.io
      - op: replace
        path: /data/NEXT_PUBLIC_VIEWER_URL
        value: https://eddieeyes.us-east-1.prd.cloudhumans.io
        
