apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  enviroment: prd

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: disturbdesk-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: eddie.us-east-1.prd.cloudhumans.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: eddie.us-east-1.prd.cloudhumans.io
  - target:
      version: v1
      kind: ConfigMap
      name: disturbdesk-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: replace
        path: /data/NEXTAUTH_URL
        value: https://eddie.us-east-1.prd.cloudhumans.io
